version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - eval $(aws sts assume-role --role-arn arn:aws:iam::793787590926:role/admin_acces_assume_role_can --role-session-name test_12 | jq -r '.Credentials| "export AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)\nexport AWS_SESSION_TOKEN=\(.SessionToken)\n"')
    
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "acess key"
      - echo $AWS_ACCESS_KEY_ID
      - docker build -t test_build:latest --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
   
